before_script:
  - apt-get update -qq
  - apt-get install -qq git
  # Setup SSH deploy keys
  - 'which ssh-agent || ( apt-get install -qq openssh-client )'
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

deploy_staging:
  type: deploy
  environment:
    name: staging
    url: https://kreditimpian.com
  script:
    - ssh kredit@128.199.69.81 "cd /home/kredit/www/master && git checkout master && git pull origin master && exit"
    - ssh kredit@167.71.217.74 "cd /home/kredit/www/development && git checkout development && git pull origin development && exit"
  only:
    - master
    - development
